WEIGHTS:
  NAV: "weights/CUTOUT_WT_True_SD_200_ckpt.99.pvp.pth"
  GAZE: "weights/closer_seed2_speed0.0872665_1648513206.ckpt.14.pth"
  PLACE: "weights/speed_sweep_seed2_speed0.174533_1648669786.ckpt.94.pth"
#  MRCNN: "weights/mask_rcnn_grayscale_0069999.pth"
  MRCNN: "weights/mask_rcnn_grayscale_0052499.pth"

DEVICE: "cuda:0"

# General env params
CTRL_HZ: 2
MAX_EPISODE_STEPS: 100

# Nav env
SUCCESS_DISTANCE: 0.25
SUCCESS_ANGLE_DIST: 5

# Gaze env
CENTER_TOLERANCE: 0.3
OBJECT_LOCK_ON_NEEDED: 2
TARGET_OBJ_ID: 3
DONT_PICK_UP: False

# Place env
EE_GRIPPER_OFFSET: [0.2, 0.0, 0.05]
SUCC_XY_DIST: 0.1
SUCC_Z_DIST: 0.20

# Base action params
MAX_LIN_VEL: 0.5  # m/s
MAX_ANG_VEL: 0.523599  # 30 degrees/s, in radians

# Arm action params
MAX_JOINT_MOVEMENT: 0.0872665  # Gaze arm speed (5 deg)
MAX_JOINT_MOVEMENT_2: 0.174533  # Place arm speed (6 deg)
INITIAL_ARM_JOINT_ANGLES: [0, -170, 120, 0, 75, 0]
ARM_LOWER_LIMITS: [-45, -180, 0, 0, -90, 0]
ARM_UPPER_LIMITS: [45, -45, 180, 0, 90, 0]
JOINT_BLACKLIST: [3, 5] # joints we can't control "arm0.el0", "arm0.wr1"
ACTUALLY_MOVE_ARM: True

# Mask RCNN
GRAYSCALE_MASK_RCNN: True
