WEIGHTS:
  NAV: "weights/CUTOUT_WT_True_SD_200_ckpt.99.pvp.pth"
  GAZE: "weights/gaze_normal_32_seed300_1649708927_ckpt.49.pth"
  PLACE: "weights/speed_sweep_seed2_speed0.174533_1648669786.ckpt.94.pth"
  MIXER: "weights/sweep_9_RT_False_WC_0_NS_128_SD_300_1650155660_ckpt_12.pth"
  MRCNN: "weights/ikea_apricot_output_model_0087499.pth"
  DEBLURGAN: "weights/fpn_mobilenet.h5"

DEVICE: "cuda:0"

# General env params
CTRL_HZ: 2.0
MAX_EPISODE_STEPS: 100

# Nav env
SUCCESS_DISTANCE: 0.3
SUCCESS_ANGLE_DIST: 5
DISABLE_OBSTACLE_AVOIDANCE: True

# Gaze env
CENTER_TOLERANCE: 0.3
OBJECT_LOCK_ON_NEEDED: 3
TARGET_OBJ_NAME: "rubiks_cube"
DONT_PICK_UP: False

# Place env
EE_GRIPPER_OFFSET: [0.2, 0.0, 0.05]
SUCC_XY_DIST: 0.1
SUCC_Z_DIST: 0.20

# Base action params
MAX_LIN_VEL: 0.5  # m/s
MAX_ANG_VEL: 0.523599  # 30 degrees/s, in radians

# Arm action params
MAX_JOINT_MOVEMENT: 0.0872665  # Gaze arm speed (5 deg)
MAX_JOINT_MOVEMENT_2: 0.174533  # Place arm speed (6 deg)
INITIAL_ARM_JOINT_ANGLES: [0, -170, 120, 0, 75, 0]
ARM_LOWER_LIMITS: [-45, -180, 0, 0, -90, 0]
ARM_UPPER_LIMITS: [45, -45, 180, 0, 90, 0]
JOINT_BLACKLIST: [3, 5] # joints we can't control "arm0.el0", "arm0.wr1"
ACTUALLY_MOVE_ARM: True

# Mask RCNN
GRAYSCALE_MASK_RCNN: True
USE_DEBLURGAN: True
IMAGE_SCALE: 1.0
# After this many time steps of not seeing the current target object, we become open to looking for new ones
FORGET_TARGET_OBJECT_STEPS: 15
