HEAD_DEPTH: "/raw_head_depth"
HAND_DEPTH: "/raw_hand_depth"
HAND_RGB: "/hand_rgb"

COMPRESSED_IMAGES: "/compressed_images"

FILTERED_HEAD_DEPTH: "/filtered_head_depth_topic"
FILTERED_HAND_DEPTH: "/filtered_hand_depth_topic"

MASK_RCNN_VIZ_TOPIC: "/mask_rcnn_visualizations"
DETECTIONS_TOPIC: "/mask_rcnn_detections"

ROBOT_STATE: "/robot_state"
TEXT_TO_SPEECH: "/text_to_speech"
